name: deploy
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'bin/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Checking out branch ${{ github.ref_name }}"
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: echo "Deploying..."
      - name: Deploy via SFTP
        uses: pressidium/lftp-mirror-action@v1
        with:
          host: ${{ secrets.FTP_HOST }}
          port: ${{ secrets.FTP_PORT }}
          user: ${{ secrets.FTP_USERNAME }}
          pass: ${{ secrets.FTP_PASSWORD }}
          remoteDir: '/public_html/wp-content/themes/tattoolab-wordpress'
          options: '--verbose'
      - run: echo "Deployed!"